Importing Numpy

In [1]:
import numpy as np

Creating Array

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


Shape

In [3]:
print(arr.shape)

(5,)


Element wise Operations

In [4]:
print(arr+2)

[3 4 5 6 7]


Combining Arrays

In [5]:
arr1 = np.array([1, 5, 6, 7])
arr2 = np.array([2, 4, 5, 7])
combined = np.concatenate((arr1, arr2))
print(combined)

[1 5 6 7 2 4 5 7]


Array Functions

Sum

In [6]:
print(np.sum(arr))

15


Mean

In [7]:
print(np.mean(arr))

3.0


Max and Min

In [8]:
print(np.max(arr))
print(np.min(arr))

5
1


Matrix

In [9]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

[[1 2]
 [3 4]]


Matrix Multiplication

In [10]:
matrix1 = np.array([[2, 3], [4, 5]])
matrix2 = np.array([[3, 4], [2, 0]])
result = np.dot(matrix1, matrix2)
print(result)

[[12  8]
 [22 16]]


Transpose

In [11]:
transposed = matrix1.T
print(transposed)

[[2 4]
 [3 5]]


Determinant

In [12]:
det = np.linalg.det(matrix1)
print(det)

-2.0
